# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGu3wYxOxXwwdXGisMtNN9jlcDo4spOC
"""

"""Group 74 - DSAD Assignment - PS18, Hash table implementation assignment"""

def initializeHash(self):
  """This function creates an empty hash table and points to null """
  pass



def insertStudentRec(StudentHashRecords, studentId, CGPA):
  """
  This function inserts the student id and corresponding CPGA into the 
  hash table. 
  The inputs need to be read from a file inputPS18.txt which contains the 
  student ID and overall graduating CGPA 
  (decimal value with a maximum of 5.0 points). 
  The file read can happen outside the function and only the
  information in every individual row needs to be passed to the function.
  """
  pass

def hallOfFame(StudentHashRecords): 
  """
  This function prints the list of all students who have
  graduated and topped their department in their year of graduation 
  (Only students who graduated should be considered. 
  Calculate the applicable year range accordingly). 
  The trigger can be read from the file promptsPS18.txt. 
  The input can be identified with the tag mentioned below -
  hallOfFame:
  """
  pass


def newCourseList(StudentHashRecords, CGPAFrom, CPGATo): 
  """
  This function prints the
  list of all students who have a CGPA within the given range and have 
  graduated in the last 5 years (Only students who graduated should be 
  considered. Calculate the applicable year range accordingly). 
  The input CGPAs can be read from the file promptsPS18.txt. The input
  can be identified with the tag mentioned below -
  courseOffer: 3.5 : 4.0
  """
  pass


def depAvg(StudentHashRecords): 
  """
  This function prints the list of all departments followed
  by the maximum CGPA and average CGPA of all students in that department. 
  The output should be captured in outputPS18.txt following format
  Output format:
  ---------- department CGPA ----------
  CSE: max: 3.5, avg: 3.4
  MEC: max: 3.5, avg: 3.4
  ECE: max: 3.5, avg: 3.4
  ARC: max: 3.5, avg: 3.4
  -------------------------------------
  """
  pass

def destroyHash(StudentHashRecords): 
  """
  This function destroys all the entries inside hash
  table. This is a clean-up code.
  """
  pass

def helperFunction():
  """
  Custom function for error checking
  """
  pass

f=open('inputPS18.txt','r')
print(f.read())
print(insertStudentRec.__doc__)
